# Shell configuration
- name: "Shell Config | Ensure dependencies for the shell configuration are installed"
  ansible.builtin.dnf:
    name:
      - git
      - tar
      - zsh
      - nano
    state: present

- name: "Shell Config | Ensure zsh is the default shell for root"
  ansible.builtin.user:
    name: "root"
    shell: "/bin/zsh"
    state: present

- name: "Shell Config | Ensure shell config is deployed for root"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
    owner: "root"
    group: "root"
    mode: preserve
  loop:
    - ".zshrc"
    - ".zsh/"

- name: "Shell Config | Ensure zsh is the default shell for specified users"
  ansible.builtin.user:
    name: "{{ item }}"
    shell: "/bin/zsh"
    state: present
  loop: "{{ users | default([]) }}"

- name: "Shell Config | Ensure shell config is deployed for user"
  ansible.builtin.copy:
    src: "{{ user_file_pair.1 }}"
    dest: "/home/{{ user_file_pair.0 }}/{{ user_file_pair.1 }}"
    owner: "{{ user_file_pair.0 }}"
    group: "{{ user_file_pair.0 }}"
    mode: preserve
  loop: "{{ users | default([]) | product(['.zshrc', '.zsh/']) | list }}"
  loop_control:
    loop_var: user_file_pair
    label: "{{ user_file_pair.0 }} - {{ user_file_pair.1 }}"
